apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx # deployment 이름
spec:
  replicas: 3 # deployment 복제 수
  selector:   #
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx # app label
    spec:
      containers:
        - name: nginx # container 이름
          image: nginx:1.14.2 # container 이미지
