apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  label:
    app: wordpress
spec:
  selector:
    app: wordpress
    tier: mysql
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
