apiVersion: apps/v1
kind: ReplicaSet # ReplicaSet
metadata:
  name: echo-rs
spec:
  replicas: 1 # 원하는 pod의 개수
  selector:   # label 체크 조건
    matchLabels:
      app: echo
      tier: app
  template:   # 생성할 pod의 명세
    metadata:
      labels:
        app: echo
        tier: app
    spec:
      containers:
        - name: echo
          image: ghcr.io/subicura/echo:v1
